apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app: descheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descheduler
  template:
    metadata:
      labels:
        app: descheduler
    spec:
      containers:
        - name: descheduler
          image: k8s.gcr.io/descheduler/descheduler:v0.24.0
          command: []  # Use default ENTRYPOINT from the image
          args:
            - --policy-config-file
            - /policy/descheduler-policy.yaml  # Pass file path as a separate argument
            - --v=2
          volumeMounts:
            - name: policy-volume
              mountPath: /policy  # This is where the ConfigMap is mounted
      volumes:
        - name: policy-volume
          configMap:
            name: descheduler-policy
      restartPolicy: Always
