apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app: descheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descheduler
  template:
    metadata:
      labels:
        app: descheduler
    spec:
      containers:
        - name: descheduler
          image: k8s.gcr.io/descheduler/descheduler:v0.24.0
          args:
            - --policy-config-file=/policy/descheduler-policy.yaml
            - --v=2
          volumeMounts:
            - name: policy-volume
              mountPath: /policy # Match this path to the args above
      volumes:
        - name: policy-volume
          configMap:
            name: descheduler-policy
      restartPolicy: Always
