apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-scheduler
spec:
  destination:
    name: ''
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: git@github.com:maartenor/kube-descheduler
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
